sudo: false
language: node_js
node_js:
- node
os:
- osx
- linux
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
- npm install -g vsce
script:
- npm run tslint
- echo "y" | vsce package
- npm test --silent
deploy:
- provider: releases
  skip_cleanup: true
  api_key: "$GIT_TOKEN"
  file_glob: true
  file: "*.vsix"
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux"
- provider: script
  skip_cleanup: true
  script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux && $TRAVIS_TAG =~ $ISPRODTAG"
env:
  global:
  - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$
  - secure: dlzFxpnvxuzDc6lsKLgO3qAM22JmuOEnEysjo2rA4hgWkx7/c9LIqzvX+b9tEFOvUj7KB98+JFbApjD2FTYxCGKoxc617YZaiuCwk0IMDDpx3AfSshewKTsy66+GVT3KGB/phhESwAM5+TkgwiT2xNTlu8C27La8WQ26RdsoNQr2Jol+78OarXia8uONqdHRL+WW3hwV1FwASiensKeUy+HnXDoDdf9s192KP/jylVuwcoRqjKX7oCJBXcHYx+N357kpUwuf7/tz2DqRIu6PML4fjqOvTYf1fhmGITIX0WT5Ios7agmJFBWDUuUo9ZsGDK1XpPKKkoGyf3n/Ja5JQ6VUJgUUk25mA0fIKqLn+Q2Zyd0E4aOh5WWROxfRgPZXEBfyYHOIwKqYenye2wksOJmlShTL/k/0bviKrReqIHz1HGWyVGnEPPq5FeOJTEZMjcZjP2p+uXbO/ozDhaiOy5qoNpmf+baqtPUclzZJYvnhvyFgHRCcfJv6ERTweB00R5URApDVGsUHlczJWNZUgKvhuFtmZZG5GBhT328VtS8hP1W4n7I/ujQeIwtgPNjNvdKlZmNTL1Ai8FcNbufDOsoHjntjKMeCWaeYrHVlxs+Q26z+2PEH3mruWcoVJNLgOEOIoTeVCKqJ6PAmBCZ0nSaMzgjd+/Hk6b1wcbhXZJ4=
  - secure: VkyjhL5zh8Bc6FVWmFpbroDoA54LWKPE+dyF8CNUnZ1YpdJXHIYjd4j2I7oVWQ+a7d8CppXnGQ5K429PKMA+GO0wNSmTzgC1MPxOxnvT90qy0Qi0RNnp/NAh6EvppR/rPhZwWfcRvgHQde3f7OgLngfGEKknuHUZYiIaW5lHrmv7uLm7OHkP5ELDrtLebQ8oVWlK0Yj47UB5H/BS7XKuXIhgVuNSoEW4g6aNCzACdfvDQtOK6+4Un9rCPk4kUrsUMEo+4TWbca1zstxu8anKTHlyTxyYoInsTKKyNzO+t1H5obS/oBxO8V91JOaEAads1DqCfoBcXVNqW5uI8IWLkY8u0DlHLj2sTye1amqla373IC4Od9zzpoQwquRlltWx1+5VFDwYPxynd964+0+hx0X/Cm5FlcZOJa2kyIMvzsx5EZx1Sz2HwZIWgQcmSY63z0Frpwr73YRArBJE+cdJ+ZTbxjHYpnF65owSmwNftpS8vltW+UM9n4Shz8yMNs1fxT8UrOaB6zjHqw4a0a7VNHHlTytM3g4hnTM0wSHqhwNFj+YQXslKOSHc3wI1otyUvDIz46wP8PDIoMln0PcSHKdogF3sSaNWMdYEk3ZS5r8yqpGuw9/KPDwHFWIThZwwnOI3J4osPeQtFZkOGgzysFlPwiapLKdXV/oZhRWdXp0=
