sudo: false
language: node_js
node_js:
- node
os:
- osx
- linux
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
- npm install -g vsce
script:
- npm run tslint
- echo "y" | vsce package
- npm test --silent
deploy:
- provider: releases
  skip_cleanup: true
  api_key: "$GIT_TOKEN"
  file_glob: true
  file: "*.vsix"
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux"
- provider: script
  skip_cleanup: true
  script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux && $TRAVIS_TAG =~ $ISPRODTAG"
env:
  global:
  - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$
  - secure: J1f3In3Q6H59EjrXaRxrZprt2MQhndCEAHt+VVBw8GLCMsA2QWvCpFh9bN1xjLTbOTOqk7tk4YgMkEwGNwoYneFrUTLFEd+TOniGm9GMfTYpXVA5RaSL7cmcn82G8DV9HNWrropAEiAaAL93eXU8xsi2olWC4UBxFrE7v5Oe59LN/zrkeW2kNV5CorL8nQOkgJORPDJAZg6O8FXIpe9+1pz/RsnjiE0z+wvoGsLYFN8iDKzJo8JbMZzNWZp2ta8/y8sHr5BvZ5PsiRxfMy8/CQQB/fQ1guajoBlH0V6XWpTkksPKv2hUjxpNpFcGQc0PC+E1B+0rkMzO5v4Ps36oZqqjwyRDmPaLFeGCiongz60UZM/dXiw7XTbU9frSC5lO4kYdaiLyD8QKX/NWMUEF2q/s4GBHLYCgyC9wjUdsAp9ikxkTfCgQMh4zb4MBGbgiySUQRrxbkm32G3Bq9Clia2lKCepNMPmZhY0Z1PcayQjqG5Mm0tjifDYX0CzMo5HcRYQ34f9biXiK+SNrDdCDMkUPLVJDel2rzXhCSL+TujPUptHSTTNc5oYyBclNxF20NYrLo3ficEYW9GpvsoW6hw8ooAC5qZ3C7juF8ufGe8MH6fYO7zVIPkH7y8nGbJyW+3phFusWMbQNgliuDp9WlAli1AzKU+A0rkro74yOVVg=
  - secure: awpMBWgCSRruCUObtzNWM6fe1wLnJvGY3j0uxp73bTUAVJsGzOLsheq1wwuZSuZuDcGVCuDG3lLRQhMyeek6BoK8vipqu19nKJTemPcvTeJ5LyVK610fYye4H7v2M90KDZggVJk1He4KfUon9ykRCKMxM+ONpZAQ3NKHGsdaXcTyadWfeim1832FXfBePSwlT6zROCjL0UpLSC3JO9af9nDN8v3Ti0kpB+MWb1f1KSV1oFBrvvabdAZ6Ulp+bijTlnj5KDaXNqpao2kGz8AP4fRGoqbMtA3Dh7keu3BW1O5jVbQehLKj0izbuiX3LaL7jRUhKwd64tQgStZnXdv6eGhSPXh5yeadQCz3d0uedmgUghVov4F0riFb+9wbr+7yCJsEghO0OUkuJtYU7IssNSQka0/5g7uYKX5fzSZ/Z00zhsjs5CA0J/qWCyO51uf9mdzkxUW7OaaS5Y+tRF1SX1RhIy2Q0V/lHAHAhTkhpwQY6gb0CcIZhC5/1qnOwtDbxS8FPQvujzw4txUpUMk46r3bV6uXVMMRynE/VY/hQO1py0JnROwhqxl3xUcqQB1P8kMl7810j4xKqjYYkBeWZtNvVG0SAB2S27qArzTD6S1bgyySVeGjj71zDz10cs7kJqjEspmTzUSyvAxInK8XUHJpeKRpZzhMSvp3dn/JQdA=
